version: '3'

services:

  hid-portal-fe:
    container_name: hid-portal-fe
    build: ./
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - api_backend

networks:
  api_backend:
    external: true
